name: default

kind: pipeline
type: docker

steps:
- name: Send stats
  image: python:3.8-slim
  network_mode: host
  environment:
    PHAB_TOKEN:
      from_secret: PHAB_TOKEN
    PHAB_URL:
      from_secret: PHAB_URL
    SLACK_HOOK_ULR:
      from_secret: SLACK_HOOK_ULR

  commands:
    - pip install poetry
    - poetry config settings.virtualenvs.create false
    - poetry install
    - poetry run send-stats

trigger:
  event:
    - push
