name: default

kind: pipeline
type: docker

steps:
- name: Send stats
  image: python:3.8-alpine

  commands:
    - pip install poetry
    - poetry config settings.virtualenvs.create false
    - poetry install
    - poetry run send-stats

trigger:
  event:
    - push